# dbt profile for Dune API connection
dbt_template:
  target: dev
  outputs:
    dev:
      type: trino
      user: dune # do not change: user is always 'dune'
      password: "{{ env_var('DUNE_API_KEY') }}"
      host: trino.api.dune.com
      port: 443
      method: ldap
      catalog: dune # do not change: catalog is always 'dune'
      # schema: REQUIRED - Set DUNE_TEAM_NAME in .env to your team name
      # Default is 'dune' if not set. To hardcode, replace: env_var('DUNE_TEAM_NAME', 'your_team')
      schema: "{{ env_var('DUNE_TEAM_NAME', 'dune') }}"
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
    prod:
      type: trino
      user: dune # do not change: user is always 'dune'
      password: "{{ env_var('DUNE_API_KEY') }}"
      host: trino.api.dune.com
      port: 443
      method: ldap
      catalog: dune # do not change: catalog is always 'dune'
      # schema: REQUIRED - Set DUNE_TEAM_NAME in .env to your team name
      # Default is 'dune' if not set. To hardcode, replace: env_var('DUNE_TEAM_NAME', 'your_team')
      schema: "{{ env_var('DUNE_TEAM_NAME', 'dune') }}"
      threads: 4
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
