version: 2

models:
  - name: unified_revenue
    description: Revenue aggregated by date and fee type (product + staking), with SOL amount, SOL price USD, SOL USD, USDC amount, and total USD.
  - name: daily_unified_revenue
    description: Daily rollup of unified revenue (SOL, USDC, and total USD).
  - name: weekly_unified_revenue
    description: Weekly rollup of unified revenue (SOL, USDC, and total USD).
  - name: monthly_unified_revenue
    description: Monthly rollup of unified revenue (SOL, USDC, and total USD).
  - name: quarterly_unified_revenue
    description: Quarterly rollup of unified revenue (SOL, USDC, and total USD).
